info:
    app:
        NAME: Spring Boot Master Class Course
        description: Master Spring Boot
        version: 1.0.0
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
    info:
        env:
            enabled: true
        java:
            enabled: true
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: on_param
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: test
        url: jdbc:h2:mem:testdb-dev-environment
        username: test
    h2:
        console:
            enabled: true
            path: /h2-dev
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    main:
        banner-mode: 'off'
